encoding: utf-8

# 站点信息
title: 'Myshantou.net'
description: 'Stories from Shantou, China'
copyright: '© 2005 - 2019 Myshantou'
keywords: 'Myshantou,Shantou'
email: demo@qq.com
twitter: https://twitter.com/myshantou

# 根路径 && 绝对路径
domain: https://myshantou.net
baseurl: ''

# 分页
paginate: 12
paginate_path: '/page:num/'

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
destination: docs
# 文章配置
permalink: /:title.html
kramdown:
  auto_ids: true
  input: GFM

# 菜单配置
menu:
  - title: Category
    url: /pages/category.html
  - title: About
    url: /pages/about.html
  - title: RSS
    url: /rss.xml

# 构建配置，勿动！！！
plugins:
  - jekyll-paginate
  - jekyll/tagging
exclude:
  - CNAME
  - README.MD
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - bin_deploy.bat
  - bin_install.bat
  - bin_start.bat
